from django.urls import path
from . import views

app_name = 'beneficiaries'

urlpatterns = [
    path('', views.BeneficiaryListView.as_view(), name='list'),
    path('new/', views.BeneficiaryCreateView.as_view(), name='create'),
    path('import/', views.BeneficiaryImportView.as_view(), name='import'),
    path('bulk/', views.BeneficiaryBulkView.as_view(), name='bulk'),
    path('duplicates/', views.DuplicateListView.as_view(), name='duplicates'),
    path('trash/', views.TrashView.as_view(), name='trash'),
    path('left/', views.LeftListView.as_view(), name='left'),
    path('merge/', views.MergeView.as_view(), name='merge'),
    path('import/template.xlsx', views.BeneficiaryImportTemplateView.as_view(), name='import_template'),
    path('<int:pk>/', views.BeneficiaryDetailView.as_view(), name='detail'),
    path('<int:pk>/edit/', views.BeneficiaryUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.BeneficiaryDeleteView.as_view(), name='delete'),
    path('<int:pk>/status/', views.BeneficiaryStatusView.as_view(), name='status'),
    path('<int:pk>/digest/', views.DigestView.as_view(), name='digest'),
    path('<int:pk>/digest/<int:digest_pk>/', views.DigestDetailView.as_view(), name='digest_detail'),
    path('<int:beneficiary_pk>/guardians/new/', views.GuardianCreateView.as_view(), name='guardian_create'),
    path('<int:beneficiary_pk>/guardians/<int:guardian_pk>/edit/', views.GuardianUpdateView.as_view(), name='guardian_update'),
    path('<int:beneficiary_pk>/certificates/new/', views.RecipientCertificateCreateView.as_view(), name='certificate_create'),
    path('<int:beneficiary_pk>/certificates/<int:cert_pk>/edit/', views.RecipientCertificateUpdateView.as_view(), name='certificate_update'),
    path('<int:beneficiary_pk>/certificates/ocr/', views.RecipientCertificateOcrView.as_view(), name='certificate_ocr'),
    path('<int:beneficiary_pk>/offices/new/', views.BeneficiaryOfficeCreateView.as_view(), name='office_create'),
    path('<int:beneficiary_pk>/offices/<int:office_pk>/edit/', views.BeneficiaryOfficeUpdateView.as_view(), name='office_update'),
    path('<int:beneficiary_pk>/offices/<int:office_pk>/delete/', views.BeneficiaryOfficeDeleteView.as_view(), name='office_delete'),
    path('<int:beneficiary_pk>/documents/upload/', views.DocumentUploadView.as_view(), name='document_upload'),
    path('<int:beneficiary_pk>/documents/<int:document_pk>/delete/', views.DocumentDeleteView.as_view(), name='document_delete'),
    path('<int:beneficiary_pk>/documents/<int:document_pk>/rename/', views.DocumentRenameView.as_view(), name='document_rename'),
    path('<int:beneficiary_pk>/assessments/new/', views.AssessmentCreateView.as_view(), name='assessment_create'),
    path('<int:beneficiary_pk>/assessments/<int:assessment_pk>/edit/', views.AssessmentUpdateView.as_view(), name='assessment_update'),
    path('<int:beneficiary_pk>/assessments/<int:assessment_pk>/delete/', views.AssessmentDeleteView.as_view(), name='assessment_delete'),
    path('<int:beneficiary_pk>/knowledge/read/', views.KnowledgeReadView.as_view(), name='knowledge_read'),
    path('<int:beneficiary_pk>/knowledge/<int:pk>/', views.KnowledgeReviewView.as_view(), name='knowledge_review'),
    path('<int:beneficiary_pk>/knowledge/<int:pk>/toggle/', views.KnowledgeToggleView.as_view(), name='knowledge_toggle'),
    path('<int:beneficiary_pk>/sheets/new/', views.DevAssessmentFormView.as_view(), name='dev_assessment_create'),
    path('<int:beneficiary_pk>/sheets/<int:sheet_pk>/', views.DevAssessmentFormView.as_view(), name='dev_assessment_edit'),
    path('<int:beneficiary_pk>/sheets/<int:sheet_pk>/pdf/', views.DevAssessmentPdfView.as_view(), name='dev_assessment_pdf'),
    path('<int:beneficiary_pk>/sheets/<int:sheet_pk>/to-plan/', views.DevAssessmentToPlanView.as_view(), name='dev_assessment_to_plan'),
    path('<int:beneficiary_pk>/sheets/<int:sheet_pk>/delete/', views.DevAssessmentDeleteView.as_view(), name='dev_assessment_delete'),
    path('<int:beneficiary_pk>/tests/new/', views.DevTestFormView.as_view(), name='dev_test_create'),
    path('<int:beneficiary_pk>/tests/read/', views.DevTestReadView.as_view(), name='dev_test_read'),
    path('<int:beneficiary_pk>/tests/<int:test_pk>/', views.DevTestFormView.as_view(), name='dev_test_edit'),
    path('<int:beneficiary_pk>/tests/<int:test_pk>/delete/', views.DevTestDeleteView.as_view(), name='dev_test_delete'),
    path('guardians/<int:guardian_pk>/regenerate-line-code/', views.RegenerateLineCodeView.as_view(), name='regenerate_line_code'),
]
