# Generated by Django 6.1.1 on 2026-09-23 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facilities", "0013_ryoiku"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Minutes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="件名")),
                ("held_on", models.DateField(verbose_name="日付")),
                (
                    "transcript",
                    models.TextField(
                        blank=True, verbose_name="話した内容（文字起こし・メモ）"
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, verbose_name="議事録（整理したもの）"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minutes",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "議事録",
                "verbose_name_plural": "議事録",
                "ordering": ["-created_at", "-pk"],
            },
        ),
    ]
