# Generated by Django 6.1.1 on 2026-09-05 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "beneficiaries",
            "0002_beneficiary_weekday_fri_beneficiary_weekday_mon_and_more",
        ),
        ("facilities", "0003_addonmaster_facilityaddonsetting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingMatrixEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("attended", "利用"),
                            ("absent", "欠席"),
                            ("transferred", "振替"),
                        ],
                        default="attended",
                        max_length=20,
                        verbose_name="状態",
                    ),
                ),
                (
                    "is_finalized",
                    models.BooleanField(default=False, verbose_name="請求確定済み"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="beneficiaries.beneficiary",
                        verbose_name="利用者",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facilities.facility",
                        verbose_name="施設",
                    ),
                ),
            ],
            options={
                "verbose_name": "請求マトリックスエントリー",
                "verbose_name_plural": "請求マトリックスエントリー",
                "ordering": ["date", "beneficiary__last_name_kana"],
                "unique_together": {("facility", "beneficiary", "date")},
            },
        ),
        migrations.CreateModel(
            name="CopaymentManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_month",
                    models.CharField(max_length=7, verbose_name="対象年月（YYYY-MM）"),
                ),
                (
                    "is_upper_limit_manager",
                    models.BooleanField(
                        default=True, verbose_name="当施設が上限額管理事業所"
                    ),
                ),
                (
                    "management_result",
                    models.CharField(
                        choices=[
                            (
                                "1",
                                "管理事業所が利用者負担額を充当したため、他事業所の徴収なし",
                            ),
                            (
                                "2",
                                "利用者負担額の合算額が、負担上限月額以下のため、調整なし",
                            ),
                            (
                                "3",
                                "利用者負担額の合算額が、負担上限月額を超過するため、調整あり",
                            ),
                        ],
                        default="2",
                        max_length=1,
                        verbose_name="管理結果",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="beneficiaries.beneficiary",
                        verbose_name="利用者",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facilities.facility",
                        verbose_name="施設",
                    ),
                ),
            ],
            options={
                "verbose_name": "上限額管理",
                "verbose_name_plural": "上限額管理",
                "ordering": ["-year_month", "beneficiary__last_name_kana"],
                "unique_together": {("facility", "beneficiary", "year_month")},
            },
        ),
        migrations.CreateModel(
            name="CopaymentOfficeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_this_office",
                    models.BooleanField(default=False, verbose_name="当施設"),
                ),
                (
                    "office_name",
                    models.CharField(max_length=200, verbose_name="事業所名"),
                ),
                (
                    "office_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="事業所番号"
                    ),
                ),
                (
                    "total_cost",
                    models.IntegerField(default=0, verbose_name="総費用額（円）"),
                ),
                (
                    "original_copayment",
                    models.IntegerField(
                        default=0, verbose_name="利用者負担額（調整前）"
                    ),
                ),
                (
                    "adjusted_copayment",
                    models.IntegerField(
                        default=0, verbose_name="利用者負担額（調整後）"
                    ),
                ),
                (
                    "management",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="office_records",
                        to="billing.copaymentmanagement",
                        verbose_name="上限額管理",
                    ),
                ),
            ],
            options={
                "verbose_name": "事業所別利用実績",
                "verbose_name_plural": "事業所別利用実績",
                "ordering": ["-is_this_office", "office_name"],
            },
        ),
        migrations.CreateModel(
            name="BillingMatrixAddon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_applied", models.BooleanField(default=True, verbose_name="適用")),
                (
                    "addon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facilities.addonmaster",
                        verbose_name="加算",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addons",
                        to="billing.billingmatrixentry",
                        verbose_name="請求エントリー",
                    ),
                ),
            ],
            options={
                "verbose_name": "請求加算",
                "verbose_name_plural": "請求加算",
                "unique_together": {("entry", "addon")},
            },
        ),
        migrations.CreateModel(
            name="BillingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_month",
                    models.CharField(max_length=7, verbose_name="対象年月（YYYY-MM）"),
                ),
                (
                    "total_units",
                    models.IntegerField(default=0, verbose_name="合計単位数"),
                ),
                (
                    "copayment",
                    models.IntegerField(default=0, verbose_name="利用者負担額"),
                ),
                (
                    "is_finalized",
                    models.BooleanField(default=False, verbose_name="確定済み"),
                ),
                (
                    "finalized_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="確定日時"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="beneficiaries.beneficiary",
                        verbose_name="利用者",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facilities.facility",
                        verbose_name="施設",
                    ),
                ),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="確定者",
                    ),
                ),
            ],
            options={
                "verbose_name": "請求記録",
                "verbose_name_plural": "請求記録",
                "ordering": ["-year_month"],
                "unique_together": {("facility", "beneficiary", "year_month")},
            },
        ),
    ]
