# Generated by Django 6.1.1 on 2026-09-05 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=50, verbose_name="姓")),
                ("first_name", models.CharField(max_length=50, verbose_name="名")),
                (
                    "last_name_kana",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="姓（かな）"
                    ),
                ),
                (
                    "first_name_kana",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="名（かな）"
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="生年月日")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女"), ("other", "その他")],
                        default="male",
                        max_length=10,
                        verbose_name="性別",
                    ),
                ),
                (
                    "disability_class",
                    models.CharField(
                        blank=True,
                        choices=[("1", "1級"), ("2", "2級")],
                        max_length=1,
                        verbose_name="障害区分",
                    ),
                ),
                (
                    "disability_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="障害種別"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "在籍中"), ("inactive", "退所")],
                        default="active",
                        max_length=10,
                        verbose_name="在籍状況",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beneficiaries",
                        to="facilities.facility",
                        verbose_name="所属施設",
                    ),
                ),
            ],
            options={
                "verbose_name": "利用者",
                "verbose_name_plural": "利用者",
                "ordering": ["last_name_kana", "first_name_kana"],
            },
        ),
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=50, verbose_name="姓")),
                ("first_name", models.CharField(max_length=50, verbose_name="名")),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("father", "父"),
                            ("mother", "母"),
                            ("other", "その他"),
                        ],
                        default="mother",
                        max_length=10,
                        verbose_name="続柄",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="電話番号"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "line_user_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="LINE User ID"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="主連絡先"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardians",
                        to="beneficiaries.beneficiary",
                        verbose_name="利用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "保護者",
                "verbose_name_plural": "保護者",
            },
        ),
        migrations.CreateModel(
            name="RecipientCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="受給者証番号"
                    ),
                ),
                (
                    "granted_days",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="支給量（日/月）"
                    ),
                ),
                (
                    "monthly_cap",
                    models.PositiveIntegerField(
                        default=0, verbose_name="負担上限月額（円）"
                    ),
                ),
                ("valid_from", models.DateField(verbose_name="有効期間（開始）")),
                ("valid_until", models.DateField(verbose_name="有効期間（終了）")),
                (
                    "municipality",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="市区町村"
                    ),
                ),
                (
                    "support_office",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="相談支援事業所"
                    ),
                ),
                (
                    "scanned_image",
                    models.ImageField(
                        blank=True,
                        upload_to="recipient_certificates/",
                        verbose_name="スキャン画像",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient_certificates",
                        to="beneficiaries.beneficiary",
                        verbose_name="利用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "受給者証",
                "verbose_name_plural": "受給者証",
                "ordering": ["-valid_until"],
            },
        ),
    ]
