# Generated by Django 6.1.1 on 2026-09-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="weekday_fri",
            field=models.BooleanField(default=False, verbose_name="金"),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="weekday_mon",
            field=models.BooleanField(default=False, verbose_name="月"),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="weekday_sat",
            field=models.BooleanField(default=False, verbose_name="土"),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="weekday_thu",
            field=models.BooleanField(default=False, verbose_name="木"),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="weekday_tue",
            field=models.BooleanField(default=False, verbose_name="火"),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="weekday_wed",
            field=models.BooleanField(default=False, verbose_name="水"),
        ),
    ]
