# Generated by Django 6.1.1 on 2026-09-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "beneficiaries",
            "0002_beneficiary_weekday_fri_beneficiary_weekday_mon_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="line_linked",
            field=models.BooleanField(default=False, verbose_name="LINE連携済み"),
        ),
    ]
