# Generated by Django 6.1.1 on 2026-09-10 23:03

import beneficiaries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0003_add_guardian_line_linked"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="line_registration_code",
            field=models.CharField(
                default=beneficiaries.models._generate_line_code,
                max_length=10,
                verbose_name="LINE登録コード",
            ),
        ),
    ]
