# Generated by Django 6.1.1 on 2026-09-11 00:33

import beneficiaries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0004_add_line_registration_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guardian",
            name="line_registration_code",
            field=models.CharField(
                default=beneficiaries.models._generate_line_code,
                max_length=10,
                unique=True,
                verbose_name="LINE登録コード",
            ),
        ),
    ]
