# Generated by Django 6.1.1 on 2026-09-14 14:51

import beneficiaries.models
import facilities.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0005_add_unique_constraint_to_line_registration_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="line_code_expires_at",
            field=models.DateTimeField(
                blank=True,
                default=beneficiaries.models._line_code_expiry,
                null=True,
                verbose_name="登録コードの有効期限",
            ),
        ),
        migrations.AlterField(
            model_name="recipientcertificate",
            name="scanned_image",
            field=models.ImageField(
                blank=True,
                upload_to=facilities.uploads.certificate_upload_to,
                verbose_name="スキャン画像",
            ),
        ),
    ]
