# Generated by Django 6.1.1 on 2026-09-18 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0007_reissue_line_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="is_severe",
            field=models.BooleanField(
                default=False, verbose_name="重症心身障害児（重身）"
            ),
        ),
        migrations.CreateModel(
            name="BeneficiaryOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="事業所名")),
                (
                    "office_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="事業所番号"
                    ),
                ),
                (
                    "is_this_office",
                    models.BooleanField(default=False, verbose_name="当施設"),
                ),
                (
                    "is_manager",
                    models.BooleanField(default=False, verbose_name="上限管理事業所"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=200, verbose_name="住所"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="電話番号"
                    ),
                ),
                (
                    "fax",
                    models.CharField(blank=True, max_length=20, verbose_name="FAX"),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="担当者名"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="備考"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="表示順"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offices",
                        to="beneficiaries.beneficiary",
                        verbose_name="利用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "利用事業所",
                "verbose_name_plural": "利用事業所",
                "ordering": ["-is_this_office", "order", "pk"],
            },
        ),
    ]
