# Generated by Django 6.1.1 on 2026-09-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0008_severe_addons_offices"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="address",
            field=models.CharField(blank=True, max_length=200, verbose_name="住所"),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="admission_date",
            field=models.DateField(blank=True, null=True, verbose_name="入所日"),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="discharge_date",
            field=models.DateField(blank=True, null=True, verbose_name="退所日"),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "選択"),
                    ("pre", "未就学"),
                    ("e1", "小1"),
                    ("e2", "小2"),
                    ("e3", "小3"),
                    ("e4", "小4"),
                    ("e5", "小5"),
                    ("e6", "小6"),
                    ("j1", "中1"),
                    ("j2", "中2"),
                    ("j3", "中3"),
                    ("h1", "高1"),
                    ("h2", "高2"),
                    ("h3", "高3"),
                    ("other", "その他"),
                ],
                max_length=10,
                verbose_name="学年",
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="has_prior_records",
            field=models.BooleanField(
                default=False, verbose_name="他システム・紙の記録がある"
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="home_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="自宅電話番号"
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="mobile_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="携帯電話番号"
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="postal_code",
            field=models.CharField(blank=True, max_length=8, verbose_name="郵便番号"),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="school_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="通学学校名"
            ),
        ),
        migrations.AddField(
            model_name="guardian",
            name="memo",
            field=models.CharField(blank=True, max_length=200, verbose_name="メモ"),
        ),
    ]
