# Generated by Django 6.1.1 on 2026-09-23 13:46

import django.db.models.deletion
import facilities.uploads
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0009_planbook"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BeneficiaryAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("assessment", "アセスメント"),
                            ("interview", "面談・聞き取り"),
                            ("test", "発達検査・評価"),
                            ("medical", "医療・関係機関の情報"),
                            ("other", "その他"),
                        ],
                        default="assessment",
                        max_length=20,
                        verbose_name="種類",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="件名")),
                ("content", models.TextField(blank=True, verbose_name="内容")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        upload_to=facilities.uploads.assessment_upload_to,
                        verbose_name="書類（PDF・写真）",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="書類の元の名前"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="beneficiaries.beneficiary",
                        verbose_name="利用者",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="登録者",
                    ),
                ),
            ],
            options={
                "verbose_name": "アセスメント・資料",
                "verbose_name_plural": "アセスメント・資料",
                "ordering": ["-date", "-pk"],
            },
        ),
    ]
