# Generated by Django 6.1.1 on 2026-09-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0011_beneficiarydocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="guardian",
            name="extra",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="取り込んだ情報"
            ),
        ),
        migrations.AddField(
            model_name="guardian",
            name="kana",
            field=models.CharField(blank=True, max_length=100, verbose_name="ふりがな"),
        ),
        migrations.AddField(
            model_name="guardian",
            name="phone2",
            field=models.CharField(blank=True, max_length=20, verbose_name="電話番号2"),
        ),
    ]
