# Generated by Django 6.1.1 on 2026-09-30 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0012_guardian_kana_phone2_extra"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BeneficiaryKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="書類の種類"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=100, verbose_name="件名"),
                ),
                (
                    "doc_date",
                    models.DateField(blank=True, null=True, verbose_name="書類の日付"),
                ),
                (
                    "issuer",
                    models.CharField(blank=True, max_length=100, verbose_name="発行元"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="要約")),
                (
                    "points",
                    models.TextField(blank=True, verbose_name="支援で気をつけること"),
                ),
                ("text", models.TextField(blank=True, verbose_name="書類の文字")),
                (
                    "proposals",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="台帳への反映案"
                    ),
                ),
                (
                    "applied",
                    models.JSONField(
                        blank=True, default=list, verbose_name="台帳に反映したもの"
                    ),
                ),
                (
                    "use_in_ai",
                    models.BooleanField(
                        default=True, verbose_name="療育記録の AI で参考にする"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "確認待ち"), ("saved", "保存済み")],
                        default="draft",
                        max_length=10,
                        verbose_name="状態",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge",
                        to="beneficiaries.beneficiaryassessment",
                        verbose_name="読み取ったアセスメント・資料",
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge",
                        to="beneficiaries.beneficiary",
                        verbose_name="利用者",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="読み取った職員",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge",
                        to="beneficiaries.beneficiarydocument",
                        verbose_name="読み取った書類",
                    ),
                ),
            ],
            options={
                "verbose_name": "書類から分かっていること",
                "verbose_name_plural": "書類から分かっていること",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part", models.CharField(default="text", max_length=10)),
                ("index", models.PositiveIntegerField(default=0)),
                ("text", models.TextField()),
                ("terms", models.JSONField(default=dict)),
                ("length", models.PositiveIntegerField(default=0)),
                (
                    "knowledge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="beneficiaries.beneficiaryknowledge",
                    ),
                ),
            ],
            options={
                "ordering": ["knowledge", "index"],
            },
        ),
    ]
