# Generated by Django 6.1.1 on 2026-10-06 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0015_beneficiary_cannot_pair"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DevelopmentAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="実施日")),
                (
                    "interviewed_with",
                    models.CharField(
                        blank=True,
                        help_text="保護者（母）・学校の先生など",
                        max_length=100,
                        verbose_name="聞き取りの相手",
                    ),
                ),
                (
                    "domains",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="領域ごとの評価"
                    ),
                ),
                (
                    "strengths",
                    models.TextField(
                        blank=True, verbose_name="本人の強み・好きなこと・得意なこと"
                    ),
                ),
                (
                    "concerns",
                    models.TextField(blank=True, verbose_name="気になること・課題"),
                ),
                (
                    "wishes_child",
                    models.TextField(blank=True, verbose_name="本人の希望"),
                ),
                (
                    "wishes_family",
                    models.TextField(blank=True, verbose_name="家族の希望"),
                ),
                (
                    "summary",
                    models.TextField(blank=True, verbose_name="まとめ・支援の方向性"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="評価者",
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="development_assessments",
                        to="beneficiaries.beneficiary",
                        verbose_name="利用者",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
            options={
                "verbose_name": "5領域アセスメント",
                "verbose_name_plural": "5領域アセスメント",
                "ordering": ["-date", "-pk"],
            },
        ),
    ]
