# Generated by Django 6.1.1 on 2026-10-06 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0016_developmentassessment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DevelopmentTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test",
                    models.CharField(
                        choices=[
                            ("kshiki", "新版K式発達検査"),
                            ("enjoji", "遠城寺式乳幼児分析的発達検査"),
                            ("kids", "KIDS 乳幼児発達スケール"),
                            ("tsumori", "津守・稲毛式乳幼児精神発達診断"),
                            ("tanaka", "田中ビネー知能検査"),
                            ("wisc", "WISC（ウィスク）"),
                            ("wppsi", "WPPSI（ウィプシ）"),
                            ("other", "その他"),
                        ],
                        default="kshiki",
                        max_length=10,
                        verbose_name="検査",
                    ),
                ),
                (
                    "test_other",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="検査名（その他）"
                    ),
                ),
                ("date", models.DateField(verbose_name="検査日")),
                (
                    "examiner",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="実施した機関・検査者"
                    ),
                ),
                (
                    "ca_months",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="生活年齢（か月）"
                    ),
                ),
                (
                    "overall_age_months",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="全体の発達年齢（か月）"
                    ),
                ),
                (
                    "overall_quotient",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="全体の指数（DQ・IQ）"
                    ),
                ),
                (
                    "results",
                    models.JSONField(
                        blank=True, default=list, verbose_name="領域ごとの結果"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="所見・メモ")),
                (
                    "source_label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="読み取った書類"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="development_tests",
                        to="beneficiaries.beneficiary",
                        verbose_name="利用者",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "発達検査",
                "verbose_name_plural": "発達検査",
                "ordering": ["-date", "-pk"],
            },
        ),
    ]
