# Generated by Django 6.1.1 on 2026-10-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0017_developmenttest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiary",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "在籍中"),
                    ("inactive", "退所"),
                    ("graduated", "卒業"),
                ],
                default="active",
                max_length=10,
                verbose_name="在籍状況",
            ),
        ),
    ]
