# Generated by Django 6.1.1 on 2026-10-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0018_beneficiary_status_graduated"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="siblings",
            field=models.ManyToManyField(
                blank=True, to="beneficiaries.beneficiary", verbose_name="きょうだい"
            ),
        ),
        migrations.AlterField(
            model_name="beneficiary",
            name="cannot_pair",
            field=models.ManyToManyField(
                blank=True,
                to="beneficiaries.beneficiary",
                verbose_name="同じ時間にできない利用者",
            ),
        ),
    ]
