# Generated by Django 6.1.1 on 2026-10-08 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0019_siblings_and_pair_same_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordDigest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField(verbose_name="期間（から）")),
                ("date_to", models.DateField(verbose_name="期間（まで）")),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        help_text="例：保護者面談・モニタリング・計画の見直し",
                        max_length=50,
                        verbose_name="使い道",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="まとめ")),
                (
                    "stats",
                    models.JSONField(blank=True, default=dict, verbose_name="数字"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digests",
                        to="beneficiaries.beneficiary",
                        verbose_name="利用者",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "面談資料",
                "verbose_name_plural": "面談資料",
                "ordering": ["-created_at", "-pk"],
            },
        ),
    ]
