# Generated by Django 6.1.1 on 2026-10-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0020_record_digest"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="no_ride_with",
            field=models.ManyToManyField(
                blank=True,
                to="beneficiaries.beneficiary",
                verbose_name="同じ車に乗せない利用者",
            ),
        ),
    ]
