# Generated by Django 6.1.1 on 2026-10-09 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0021_no_ride_with"),
        ("facilities", "0021_facility_use_daily_ops"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedBeneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beneficiary_pk",
                    models.PositiveIntegerField(verbose_name="元の番号"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="氏名")),
                (
                    "status_label",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="消したときの在籍状況"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="消した日時"),
                ),
                (
                    "payload",
                    models.JSONField(default=list, verbose_name="消えた記録（戻す順）"),
                ),
                (
                    "relinks",
                    models.JSONField(
                        default=list, verbose_name="戻すときに結び直すもの"
                    ),
                ),
                (
                    "files",
                    models.JSONField(default=list, verbose_name="書類のファイル"),
                ),
                ("counts", models.JSONField(default=list, verbose_name="件数")),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deleted_beneficiaries",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "ごみ箱の利用者",
                "verbose_name_plural": "ごみ箱の利用者",
                "ordering": ["-deleted_at", "-pk"],
            },
        ),
    ]
