# Generated by Django 6.1.1 on 2026-10-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0022_trash"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="line_send_journal",
            field=models.BooleanField(default=True, verbose_name="日誌を LINE で送る"),
        ),
    ]
