# Generated by Django 6.1.1 on 2026-09-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="施設名")),
                (
                    "office_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="事業所番号"
                    ),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=200, verbose_name="住所"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="電話番号"
                    ),
                ),
                (
                    "line_channel_access_token",
                    models.TextField(
                        blank=True, verbose_name="LINEチャネルアクセストークン"
                    ),
                ),
                (
                    "line_channel_secret",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="LINEチャネルシークレット",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "施設",
                "verbose_name_plural": "施設",
            },
        ),
    ]
