# Generated by Django 6.1.1 on 2026-09-05 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="base_unit_count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="1日あたり基本報酬単位数"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="is_new_facility_r8",
            field=models.BooleanField(
                default=False,
                help_text="令和8年6月1日以降に新規指定された事業所の場合はチェック",
                verbose_name="令和8年6月以降新規指定事業所",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="region_category",
            field=models.CharField(
                choices=[
                    ("1", "1級地（東京23区等）"),
                    ("2", "2級地"),
                    ("3", "3級地"),
                    ("4", "4級地"),
                    ("5", "5級地"),
                    ("6", "6級地"),
                    ("7", "7級地"),
                    ("other", "その他"),
                ],
                default="other",
                max_length=10,
                verbose_name="地域区分",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="standard_close_time",
            field=models.TimeField(
                blank=True,
                help_text="例：17:00。延長支援加算の自動チェックに使います。",
                null=True,
                verbose_name="通常終了時刻",
            ),
        ),
        migrations.CreateModel(
            name="SupportContentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="タグ名")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="表示順"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_content_tags",
                        to="facilities.facility",
                        verbose_name="施設",
                    ),
                ),
            ],
            options={
                "verbose_name": "支援内容タグ",
                "verbose_name_plural": "支援内容タグ",
                "ordering": ["order", "name"],
            },
        ),
    ]
