# Generated by Django 6.1.1 on 2026-09-05 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "facilities",
            "0002_facility_base_unit_count_facility_is_new_facility_r8_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AddonMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="加算名")),
                (
                    "addon_type",
                    models.CharField(
                        choices=[
                            ("individual", "個別加算（利用者×日単位）"),
                            ("facility", "体制加算（施設全体・月単位）"),
                        ],
                        default="individual",
                        max_length=20,
                        verbose_name="加算種別",
                    ),
                ),
                ("unit_count", models.IntegerField(default=0, verbose_name="単位数")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="算定要件の概要"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
            ],
            options={
                "verbose_name": "加算マスタ",
                "verbose_name_plural": "加算マスタ",
                "ordering": ["addon_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="FacilityAddonSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=False, verbose_name="算定する"),
                ),
                (
                    "addon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facilities.addonmaster",
                        verbose_name="加算",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facilities.facility",
                        verbose_name="施設",
                    ),
                ),
            ],
            options={
                "verbose_name": "施設加算設定",
                "verbose_name_plural": "施設加算設定",
                "unique_together": {("facility", "addon")},
            },
        ),
    ]
