# Generated by Django 6.1.1 on 2026-09-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0003_addonmaster_facilityaddonsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportcontenttag",
            name="price",
            field=models.PositiveIntegerField(
                default=0,
                help_text="0 のときは実費請求しない",
                verbose_name="実費単価（円/回）",
            ),
        ),
    ]
