# Generated by Django 6.1.1 on 2026-09-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0004_supportcontenttag_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="brand_color",
            field=models.CharField(
                blank=True,
                help_text="#4e7d89 のような16進数。空なら標準色",
                max_length=7,
                verbose_name="コーポレートカラー",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="facility_logos/",
                verbose_name="ロゴ画像",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="term_beneficiary",
            field=models.CharField(
                default="利用者",
                help_text="例：利用児／園児／ご利用者様",
                max_length=20,
                verbose_name="利用者の呼び方",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="term_staff",
            field=models.CharField(
                default="職員",
                help_text="例：支援員／先生／職員",
                max_length=20,
                verbose_name="職員の呼び方",
            ),
        ),
    ]
