# Generated by Django 6.1.1 on 2026-09-14 14:51

import facilities.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0007_facility_form_set"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=facilities.uploads.logo_upload_to,
                verbose_name="ロゴ画像",
            ),
        ),
    ]
