# Generated by Django 6.1.1 on 2026-09-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0009_concurrency"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="use_reservation",
            field=models.BooleanField(
                default=False,
                help_text="1日の枠・キャンセル待ち・公式LINEからの申し込みを扱います。",
                verbose_name="予約管理を使う",
            ),
        ),
    ]
