# Generated by Django 6.1.1 on 2026-09-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0010_reservations"),
    ]

    operations = [
        migrations.AddField(
            model_name="addonmaster",
            name="code",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="サービスコード"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="base_unit_count_severe",
            field=models.IntegerField(
                blank=True,
                help_text="重症心身障害児の利用者に使う単位数。空なら通常の単位数を使います。",
                null=True,
                verbose_name="重身の1日あたり基本報酬単位数",
            ),
        ),
        migrations.AddField(
            model_name="facilityaddonsetting",
            name="code",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="サービスコード（事業所）"
            ),
        ),
        migrations.AddField(
            model_name="facilityaddonsetting",
            name="unit_count",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="単位数（事業所）"
            ),
        ),
    ]
