# Generated by Django 6.1.1 on 2026-09-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0011_severe_addons_offices"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="address2",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="住所2（建物名など）"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="company_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="会社名"),
        ),
        migrations.AddField(
            model_name="facility",
            name="layout",
            field=models.CharField(
                choices=[
                    ("standard", "標準（記録・予定・請求まで全部）"),
                    (
                        "planbook",
                        "計画書中心（シンプル：利用者・完了期日一覧・スタッフ・保護者・連絡帳・施設）",
                    ),
                ],
                default="standard",
                max_length=20,
                verbose_name="画面の型",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="postal_code",
            field=models.CharField(blank=True, max_length=8, verbose_name="郵便番号"),
        ),
        migrations.AddField(
            model_name="facility",
            name="representative_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="代表者メールアドレス"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="representative_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="代表者名"),
        ),
    ]
