# Generated by Django 6.1.1 on 2026-09-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0012_planbook"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="use_therapy_record",
            field=models.BooleanField(
                default=False,
                help_text="利用者ごとの留意点と、1回ごとの療育の記録（やったこと①〜⑤・担当・本文）。用紙と同じ形で印刷できます。",
                verbose_name="療育記録を使う",
            ),
        ),
    ]
