# Generated by Django 6.1.1 on 2026-09-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0013_ryoiku"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="staff_signup_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=12, verbose_name="職員登録コード"
            ),
        ),
    ]
