# Generated by Django 6.1.1 on 2026-09-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0014_staff_signup_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="staff_signup_open",
            field=models.BooleanField(
                default=False, verbose_name="職員登録コードなしで申し込みを受け付ける"
            ),
        ),
    ]
