# Generated by Django 6.1.1 on 2026-09-24 10:53

from django.db import migrations, models

# 発達支援ルーム　ゆあーず（2026-09-24 依頼）：請求機能と予定（来所予定・出欠）は使わないので隠す。
# 名前が一致する事業所だけを書き換える（0009_rename_ryoiku_facility と同じ考え方）
RYOIKU_NAME = '発達支援ルーム　ゆあーず'


def turn_off_for_ryoiku(apps, schema_editor):
    Facility = apps.get_model('facilities', 'Facility')
    Facility.objects.filter(name=RYOIKU_NAME).update(use_billing=False, use_schedule=False)


def turn_back_on(apps, schema_editor):
    Facility = apps.get_model('facilities', 'Facility')
    Facility.objects.filter(name=RYOIKU_NAME).update(use_billing=True, use_schedule=True)


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0015_staff_signup_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="use_schedule",
            field=models.BooleanField(
                default=True,
                help_text="月のカレンダーに来所予定を入れて出欠を付ける画面。予約管理で枠を扱う事業所は使わなくてよい。",
                verbose_name="予定（来所予定・出欠）を使う",
            ),
        ),
        migrations.RunPython(turn_off_for_ryoiku, turn_back_on),
    ]
