# Generated by Django 6.1.1 on 2026-09-24 11:09

from django.db import migrations, models

# 発達支援ルーム　ゆあーず（2026-09-24 依頼）：メニューを「基本機能／お試し／設定」にし、
# お試し（記録・支援計画）の AI は 20 回まで。名前が一致する事業所だけを書き換える
RYOIKU_NAME = '発達支援ルーム　ゆあーず'
TRIAL_AI_LIMIT = 20


def set_ryoiku(apps, schema_editor):
    Facility = apps.get_model('facilities', 'Facility')
    Facility.objects.filter(name=RYOIKU_NAME).update(layout='ryoiku', trial_ai_limit=TRIAL_AI_LIMIT)


def unset_ryoiku(apps, schema_editor):
    Facility = apps.get_model('facilities', 'Facility')
    Facility.objects.filter(name=RYOIKU_NAME).update(layout='standard', trial_ai_limit=0)


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0016_use_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="trial_ai_limit",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="お試しの AI の回数の上限（0＝制限なし）"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="trial_ai_used",
            field=models.PositiveIntegerField(
                default=0, verbose_name="お試しの AI を使った回数"
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="layout",
            field=models.CharField(
                choices=[
                    ("standard", "標準（記録・予定・請求まで全部）"),
                    (
                        "planbook",
                        "計画書中心（シンプル：利用者・完了期日一覧・スタッフ・保護者・連絡帳・施設）",
                    ),
                    (
                        "ryoiku",
                        "療育（ゆあーず：基本機能＝ホーム・利用者情報・予約・療育記録・議事録・LINE連携／お試し＝記録・支援計画）",
                    ),
                ],
                default="standard",
                max_length=20,
                verbose_name="画面の型",
            ),
        ),
        migrations.RunPython(set_ryoiku, unset_ryoiku),
    ]
