# Generated by Django 6.1.1 on 2026-10-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0018_facility_speech_words"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="use_dev_assessment",
            field=models.BooleanField(
                default=False,
                help_text="健康・生活／運動・感覚／認知・行動／言語・コミュニケーション／人間関係・社会性の5領域を5段階で評価する用紙。利用者情報から作り、A4で印刷できます。",
                verbose_name="5領域アセスメントを使う",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="use_transport",
            field=models.BooleanField(
                default=False,
                help_text="車両と運転手を登録し、利用者ごとの送迎（迎え・送り・場所）から日ごとの配車表を作ります。",
                verbose_name="送迎・配車を使う",
            ),
        ),
    ]
