# Generated by Django 6.1.1 on 2026-10-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0019_transport_dev_assessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="use_survey",
            field=models.BooleanField(
                default=False,
                help_text="保護者評価アンケート（ログインなしの回答ページ・LINE や QR で配る・集計）と事業所の自己評価、公表用の PDF。ガイドラインで年 1 回の実施と公表が求められているもの。",
                verbose_name="アンケート・自己評価を使う",
            ),
        ),
    ]
