# Generated by Django 6.1.1 on 2026-10-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0020_use_survey"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="use_daily_ops",
            field=models.BooleanField(
                default=False,
                help_text="クラス（小集団）の週間の活動計画と当日の記録（各児の療育記録に写す）、健康・生活の記録（体温・食事・排せつ・午睡・服薬と引き渡しカード）、発達検査の結果の推移。",
                verbose_name="毎日の運営を使う",
            ),
        ),
    ]
