# Generated by Django 6.1.1 on 2026-10-09 06:03

from django.db import migrations, models


def rename_facility(apps, schema_editor):
    """事業所名は「はぴねす」「はぴりす」ではなく「はびりす」が正しい（2026-10-09 依頼者）。名前がそのままの事業所を書き換える"""
    Facility = apps.get_model('facilities', 'Facility')
    Facility.objects.filter(name__in=('はぴねす', 'はぴりす')).update(name='はびりす')


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0021_facility_use_daily_ops"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="form_set",
            field=models.CharField(
                choices=[
                    ("standard", "標準"),
                    (
                        "happiness",
                        "はびりす様式（関係機関連携報告書・個別支援計画書 別紙1／詳細版・専門的支援実施計画書）",
                    ),
                ],
                default="standard",
                max_length=20,
                verbose_name="帳票様式",
            ),
        ),
            migrations.RunPython(rename_facility, migrations.RunPython.noop),
    ]
