# Generated by Django 6.1.1 on 2026-10-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0022_happiness_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="word_rules",
            field=models.TextField(
                blank=True, verbose_name="言葉づかいの辞書（保存前に知らせる言葉）"
            ),
        ),
    ]
