# Generated by Django 6.1.1 on 2026-10-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0023_word_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="line_auto_send",
            field=models.BooleanField(
                default=False, verbose_name="日誌を確定したら保護者へ LINE を自動で送る"
            ),
        ),
    ]
