# Generated by Django 6.1.1 on 2026-10-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0024_line_auto_send"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="journal_min_chars",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="観察・支援・反応の最低字数"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="journal_required",
            field=models.JSONField(
                blank=True, default=list, verbose_name="日誌を確定するのに要る項目"
            ),
        ),
    ]
