# Generated by Django 6.1.1 on 2026-09-06 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facilities", "0003_addonmaster_facilityaddonsetting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EsignatureRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signer_name",
                    models.CharField(max_length=100, verbose_name="署名者氏名"),
                ),
                (
                    "relationship",
                    models.CharField(blank=True, max_length=50, verbose_name="続柄"),
                ),
                (
                    "signed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="署名日時"),
                ),
                (
                    "signature_image",
                    models.ImageField(
                        upload_to="signatures/%Y/%m/", verbose_name="署名画像"
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("daily_record", "日次記録"),
                            ("support_plan", "個別支援計画"),
                            ("monitoring", "モニタリング"),
                        ],
                        max_length=30,
                        verbose_name="対象種別",
                    ),
                ),
                ("target_id", models.PositiveIntegerField(verbose_name="対象ID")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作者",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facilities.facility",
                        verbose_name="施設",
                    ),
                ),
            ],
            options={
                "verbose_name": "電子サイン記録",
                "verbose_name_plural": "電子サイン記録",
                "ordering": ["-signed_at"],
            },
        ),
    ]
