# Generated by Django 6.1.1 on 2026-09-14 14:51

import facilities.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("esignatures", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="esignaturerecord",
            name="signature_image",
            field=models.ImageField(
                upload_to=facilities.uploads.signature_upload_to,
                verbose_name="署名画像",
            ),
        ),
    ]
