# Generated by Django 6.1.1 on 2026-09-12 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beneficiaries", "0005_add_unique_constraint_to_line_registration_code"),
        ("facilities", "0003_addonmaster_facilityaddonsetting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="計画名")),
                (
                    "current_step",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "アセスメント"),
                            (2, "計画（原案）の作成"),
                            (3, "担当者会議"),
                            (4, "説明・同意・交付"),
                            (5, "モニタリング"),
                        ],
                        default=1,
                        verbose_name="現在のステップ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "作成中"),
                            ("active", "実施中"),
                            ("closed", "終了"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="状態",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="終了日時"
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_plans",
                        to="beneficiaries.beneficiary",
                        verbose_name="利用者",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="support_plans",
                        to="facilities.facility",
                        verbose_name="施設",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_support_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="児童発達支援管理責任者",
                    ),
                ),
                (
                    "predecessor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="successor",
                        to="support_plans.supportplan",
                        verbose_name="前の計画",
                    ),
                ),
            ],
            options={
                "verbose_name": "個別支援計画",
                "verbose_name_plural": "個別支援計画",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完了日時"
                    ),
                ),
                (
                    "meeting_date",
                    models.DateField(blank=True, null=True, verbose_name="開催日"),
                ),
                (
                    "attendees",
                    models.TextField(
                        blank=True,
                        help_text="職員・関係機関など",
                        verbose_name="出席者",
                    ),
                ),
                (
                    "beneficiary_attended",
                    models.BooleanField(default=False, verbose_name="本人が出席した"),
                ),
                (
                    "guardian_attended",
                    models.BooleanField(default=False, verbose_name="保護者が出席した"),
                ),
                (
                    "absence_reason",
                    models.CharField(
                        blank=True,
                        help_text="原則として本人の出席が必要。欠席の場合は理由を記録する",
                        max_length=200,
                        verbose_name="本人が出席しなかった理由",
                    ),
                ),
                (
                    "opinions",
                    models.TextField(blank=True, verbose_name="原案への意見・協議内容"),
                ),
                (
                    "revised",
                    models.BooleanField(default=False, verbose_name="原案を修正した"),
                ),
                (
                    "revision_summary",
                    models.TextField(blank=True, verbose_name="修正内容"),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="完了者",
                    ),
                ),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting",
                        to="support_plans.supportplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "担当者会議",
                "verbose_name_plural": "担当者会議",
            },
        ),
        migrations.CreateModel(
            name="PlanGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[("long", "長期目標"), ("short", "短期目標")],
                        default="short",
                        max_length=10,
                        verbose_name="区分",
                    ),
                ),
                ("content", models.CharField(max_length=200, verbose_name="目標")),
                (
                    "target_date",
                    models.DateField(blank=True, null=True, verbose_name="達成時期"),
                ),
                (
                    "support_content",
                    models.TextField(
                        blank=True,
                        help_text="短期目標では必須。誰が・いつ・どのように支援するか",
                        verbose_name="具体的な支援内容",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        help_text="例：週3回・活動の前半30分",
                        max_length=100,
                        verbose_name="頻度・時間",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="support_plans.supportplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "目標",
                "verbose_name_plural": "目標",
                "ordering": ["goal_type", "order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="PlanDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完了日時"
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="計画期間（開始）"
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="計画期間（終了）"
                    ),
                ),
                (
                    "policy",
                    models.TextField(blank=True, verbose_name="総合的な支援の方針"),
                ),
                (
                    "family_wishes",
                    models.TextField(
                        blank=True, verbose_name="本人・家族の意向（計画書に記載）"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="留意事項")),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="完了者",
                    ),
                ),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft",
                        to="support_plans.supportplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "計画（原案）",
                "verbose_name_plural": "計画（原案）",
            },
        ),
        migrations.CreateModel(
            name="MonitoringRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="実施日")),
                (
                    "interviewed_with",
                    models.CharField(
                        blank=True,
                        help_text="例：本人・母",
                        max_length=100,
                        verbose_name="面談相手",
                    ),
                ),
                (
                    "implementation",
                    models.TextField(
                        help_text="支援内容の実施状況",
                        verbose_name="計画通りに支援できているか",
                    ),
                ),
                (
                    "achievement",
                    models.CharField(
                        choices=[
                            ("achieved", "達成"),
                            ("progressing", "順調"),
                            ("partial", "一部達成"),
                            ("not_yet", "未達成"),
                        ],
                        default="progressing",
                        max_length=20,
                        verbose_name="目標の達成状況",
                    ),
                ),
                (
                    "achievement_detail",
                    models.TextField(
                        blank=True, verbose_name="達成状況の詳細・本人の変化"
                    ),
                ),
                (
                    "review_needed",
                    models.BooleanField(
                        default=False, verbose_name="計画の見直しが必要"
                    ),
                ),
                (
                    "review_reason",
                    models.TextField(
                        blank=True, verbose_name="見直しが必要な理由・次の計画への課題"
                    ),
                ),
                (
                    "next_due",
                    models.DateField(
                        blank=True, null=True, verbose_name="次回モニタリング期限"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conducted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="担当職員",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_records",
                        to="support_plans.supportplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "モニタリング記録",
                "verbose_name_plural": "モニタリング記録",
                "ordering": ["-date", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="Monitoring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完了日時"
                    ),
                ),
                (
                    "interval_months",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="サービスの種類に応じて3〜6か月に1回以上",
                        verbose_name="モニタリング間隔（か月）",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="完了者",
                    ),
                ),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring",
                        to="support_plans.supportplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "モニタリング設定",
                "verbose_name_plural": "モニタリング設定",
            },
        ),
        migrations.CreateModel(
            name="ConsentDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完了日時"
                    ),
                ),
                (
                    "explained_date",
                    models.DateField(blank=True, null=True, verbose_name="説明日"),
                ),
                (
                    "explained_to",
                    models.CharField(
                        blank=True,
                        help_text="例：本人・母",
                        max_length=100,
                        verbose_name="説明した相手",
                    ),
                ),
                (
                    "consent_method",
                    models.CharField(
                        choices=[
                            ("esign", "電子サイン"),
                            ("paper", "書面（署名・押印）"),
                        ],
                        default="esign",
                        max_length=10,
                        verbose_name="同意の方法",
                    ),
                ),
                (
                    "consent_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="同意日（書面の場合）"
                    ),
                ),
                (
                    "consent_signer",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="署名者（書面の場合）"
                    ),
                ),
                (
                    "delivered_to_user_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="本人・家族への交付日"
                    ),
                ),
                (
                    "delivered_to_office_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="相談支援事業所への交付日"
                    ),
                ),
                (
                    "consultation_office",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="相談支援事業所名"
                    ),
                ),
                (
                    "service_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="サービス開始日"
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="完了者",
                    ),
                ),
                (
                    "explained_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="説明した職員",
                    ),
                ),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent",
                        to="support_plans.supportplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "説明・同意・交付",
                "verbose_name_plural": "説明・同意・交付",
            },
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完了日時"
                    ),
                ),
                (
                    "interview_date",
                    models.DateField(blank=True, null=True, verbose_name="面談日"),
                ),
                (
                    "interviewed_with",
                    models.CharField(
                        blank=True,
                        help_text="例：本人・母",
                        max_length=100,
                        verbose_name="面談相手",
                    ),
                ),
                (
                    "condition",
                    models.TextField(
                        blank=True,
                        help_text="発達・健康面・得意なこと／苦手なこと・コミュニケーションの特徴など",
                        verbose_name="心身の状況",
                    ),
                ),
                (
                    "environment",
                    models.TextField(
                        blank=True,
                        help_text="家庭・学校・関係機関・生活リズムなど",
                        verbose_name="置かれている環境",
                    ),
                ),
                (
                    "wishes",
                    models.TextField(
                        blank=True,
                        help_text="本人の希望、家族の希望",
                        verbose_name="希望する生活",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="その他の情報")),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="完了者",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="面談担当",
                    ),
                ),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment",
                        to="support_plans.supportplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "アセスメント",
                "verbose_name_plural": "アセスメント",
            },
        ),
    ]
