# Generated by Django 6.1.1 on 2026-09-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0006_activity_viewpoints"),
        ("support_plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plangoal",
            name="evidence_records",
            field=models.ManyToManyField(
                blank=True,
                related_name="evidence_for_goals",
                to="records.dailyrecord",
                verbose_name="根拠になった記録",
            ),
        ),
    ]
