# Generated by Django 6.1.1 on 2026-09-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support_plans", "0003_form_extra"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="consentdelivery",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="monitoring",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="plandraft",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="plangoal",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="staffmeeting",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
