# Generated by Django 6.1.1 on 2026-10-06 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beneficiaries", "0017_developmenttest"),
        ("facilities", "0021_facility_use_daily_ops"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="例：ひよこ組・午前の小集団",
                        max_length=50,
                        verbose_name="クラス名",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#4e7d89", max_length=10, verbose_name="色"
                    ),
                ),
                (
                    "weekdays",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="0=月 … 5=土",
                        verbose_name="活動する曜日",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="いつもの開始時刻"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="メモ"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="使っている"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="並び順"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_groups",
                        to="facilities.facility",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="class_groups",
                        to="beneficiaries.beneficiary",
                        verbose_name="メンバー",
                    ),
                ),
            ],
            options={
                "verbose_name": "クラス",
                "verbose_name_plural": "クラス",
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="HealthProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allergies",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="アレルギー・食べられないもの",
                    ),
                ),
                (
                    "medications",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="服薬（薬の名前・時間）",
                    ),
                ),
                (
                    "seizure",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="発作・医療的ケア"
                    ),
                ),
                (
                    "other",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="その他の注意"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_profile",
                        to="beneficiaries.beneficiary",
                    ),
                ),
            ],
            options={
                "verbose_name": "健康の注意",
                "verbose_name_plural": "健康の注意",
            },
        ),
        migrations.CreateModel(
            name="GroupSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="開始時刻"),
                ),
                (
                    "aim",
                    models.CharField(blank=True, max_length=200, verbose_name="ねらい"),
                ),
                (
                    "activities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="活動（①〜⑤）"
                    ),
                ),
                (
                    "materials",
                    models.CharField(blank=True, max_length=300, verbose_name="準備物"),
                ),
                (
                    "staff_name",
                    models.CharField(blank=True, max_length=100, verbose_name="担当"),
                ),
                ("body", models.TextField(blank=True, verbose_name="全体の様子")),
                (
                    "present",
                    models.JSONField(
                        blank=True, default=list, verbose_name="参加した利用者（ID）"
                    ),
                ),
                (
                    "notes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="一人ずつのひとこと"
                    ),
                ),
                (
                    "record_ids",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="写した療育記録"
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="療育記録に写した日時"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="daily.classgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "クラスの活動",
                "verbose_name_plural": "クラスの活動",
                "ordering": ["date", "start_time", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "date"), name="uniq_group_session_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HealthLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "temp_arrival",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="体温（来所時）",
                    ),
                ),
                (
                    "temp_other",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        verbose_name="体温（そのほか）",
                    ),
                ),
                (
                    "meal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "－"),
                            ("all", "完食"),
                            ("most", "ほぼ食べた"),
                            ("half", "半分"),
                            ("little", "少し"),
                            ("none", "食べない"),
                            ("na", "なし（食事の時間なし）"),
                        ],
                        max_length=10,
                        verbose_name="食事・おやつ",
                    ),
                ),
                (
                    "meal_note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="食事のメモ"
                    ),
                ),
                (
                    "urine",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="おしっこ（回）"
                    ),
                ),
                (
                    "stool",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="うんち（回）"
                    ),
                ),
                (
                    "toilet_note",
                    models.CharField(
                        blank=True,
                        help_text="トイレで成功・おむつ交換・便の様子など",
                        max_length=200,
                        verbose_name="排せつのメモ",
                    ),
                ),
                (
                    "nap_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="午睡（分）"
                    ),
                ),
                (
                    "medication_given",
                    models.BooleanField(default=False, verbose_name="薬を飲ませた"),
                ),
                (
                    "medication_note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="服薬のメモ"
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "－"),
                            ("good", "ごきげん"),
                            ("normal", "ふつう"),
                            ("tired", "疲れぎみ"),
                            ("bad", "不機嫌・体調不良"),
                        ],
                        max_length=10,
                        verbose_name="機嫌・体調",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        verbose_name="その他（けが・ひやりとしたこと・連絡）",
                    ),
                ),
                (
                    "handed_to",
                    models.CharField(
                        blank=True,
                        help_text="母・父・祖母・送迎 など",
                        max_length=50,
                        verbose_name="引き渡した相手",
                    ),
                ),
                (
                    "handed_at",
                    models.TimeField(
                        blank=True, null=True, verbose_name="引き渡しの時刻"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_logs",
                        to="beneficiaries.beneficiary",
                        verbose_name="利用者",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_logs",
                        to="facilities.facility",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "健康の記録",
                "verbose_name_plural": "健康の記録",
                "ordering": ["-date", "beneficiary__last_name_kana"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("beneficiary", "date"), name="uniq_health_log_day"
                    )
                ],
            },
        ),
    ]
