# Generated by Django 6.1.1 on 2026-09-15 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beneficiaries", "0007_reissue_line_codes"),
        ("facilities", "0010_reservations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="お名前")),
                (
                    "kana",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ふりがな"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="電話番号"
                    ),
                ),
                (
                    "line_user_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="LINEのユーザーID"
                    ),
                ),
                (
                    "notify_enabled",
                    models.BooleanField(default=True, verbose_name="LINEで通知する"),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="備考"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "children",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reservation_customers",
                        to="beneficiaries.beneficiary",
                        verbose_name="担当する利用者",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_customers",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "顧客（予約の連絡先）",
                "verbose_name_plural": "顧客（予約の連絡先）",
                "ordering": ["kana", "name"],
            },
        ),
        migrations.CreateModel(
            name="LineInbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(max_length=100, verbose_name="メッセージID"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("user", "個別"),
                            ("group", "グループ"),
                            ("room", "複数人トーク"),
                        ],
                        default="user",
                        max_length=10,
                    ),
                ),
                ("line_user_id", models.CharField(blank=True, max_length=100)),
                ("group_id", models.CharField(blank=True, max_length=100)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=100, verbose_name="表示名"),
                ),
                ("text", models.TextField(blank=True, verbose_name="本文")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "未処理"),
                            ("done", "反映ずみ"),
                            ("ignored", "見送り"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result_note",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="処理の結果"
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_inbox",
                        to="facilities.facility",
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "LINEの受信",
                "verbose_name_plural": "LINEの受信",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="予約日")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "予約"),
                            ("waitlist", "キャンセル待ち"),
                            ("cancelled", "取消"),
                            ("declined", "お断り"),
                        ],
                        default="confirmed",
                        max_length=20,
                        verbose_name="状態",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("staff", "職員"), ("line", "公式LINE")],
                        default="staff",
                        max_length=10,
                        verbose_name="入口",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="備考"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="取消日時"
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="beneficiaries.beneficiary",
                        verbose_name="利用者",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="reservations.customer",
                        verbose_name="連絡先",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "予約",
                "verbose_name_plural": "予約",
                "ordering": ["date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReservationNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("accepted", "受付"),
                            ("waitlisted", "キャンセル待ち"),
                            ("promoted", "繰り上げ確定"),
                            ("cancelled", "取消"),
                            ("declined", "お断り"),
                            ("reminder", "前日のお知らせ"),
                            ("vacancy", "空き枠"),
                            ("group", "予約の増減（グループ）"),
                        ],
                        max_length=20,
                        verbose_name="種類",
                    ),
                ),
                (
                    "date",
                    models.DateField(blank=True, null=True, verbose_name="対象日"),
                ),
                (
                    "to_line_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="送信先のLINE ID"
                    ),
                ),
                ("body", models.TextField(verbose_name="文面")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "送信待ち"),
                            ("sent", "送信ずみ"),
                            ("failed", "送信できず"),
                            ("manual", "手渡し（コピーして送る）"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="状態",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="エラー内容"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="送信日時"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notices",
                        to="reservations.customer",
                        verbose_name="宛先の顧客",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_notices",
                        to="facilities.facility",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notices",
                        to="reservations.reservation",
                        verbose_name="対象の予約",
                    ),
                ),
            ],
            options={
                "verbose_name": "予約の通知",
                "verbose_name_plural": "予約の通知",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReservationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="1日の枠（人）"
                    ),
                ),
                (
                    "allow_waitlist",
                    models.BooleanField(
                        default=True, verbose_name="満枠のときキャンセル待ちで受ける"
                    ),
                ),
                (
                    "closed_weekdays",
                    models.JSONField(blank=True, default=list, verbose_name="休業曜日"),
                ),
                (
                    "signature",
                    models.CharField(
                        blank=True,
                        help_text="通知の末尾に付きます（例：放課後等デイサービス なゆた）",
                        max_length=100,
                        verbose_name="通知の署名",
                    ),
                ),
                (
                    "auto_send",
                    models.BooleanField(
                        default=False, verbose_name="反映したら送信待ちをその場で送る"
                    ),
                ),
                (
                    "notify_group_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="増減を知らせるLINEグループ",
                    ),
                ),
                (
                    "notify_group_label",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="そのグループの呼び名"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_setting",
                        to="facilities.facility",
                        verbose_name="施設",
                    ),
                ),
            ],
            options={
                "verbose_name": "予約の設定",
                "verbose_name_plural": "予約の設定",
            },
        ),
        migrations.CreateModel(
            name="ClosedDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="休業日")),
                (
                    "reason",
                    models.CharField(blank=True, max_length=100, verbose_name="理由"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_closed_dates",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "臨時休業日",
                "verbose_name_plural": "臨時休業日",
                "ordering": ["date"],
                "unique_together": {("facility", "date")},
            },
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("line_user_id", ""), _negated=True),
                fields=("facility", "line_user_id"),
                name="uniq_customer_line_user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lineinbox",
            unique_together={("facility", "message_id")},
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["facility", "date", "status"],
                name="reservation_facilit_c9c956_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("confirmed", "waitlist"))),
                fields=("beneficiary", "date"),
                name="uniq_active_reservation",
            ),
        ),
    ]
