# Generated by Django 6.1.1 on 2026-09-20 13:03

import django.db.models.deletion
import reservations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0009_planbook"),
        ("facilities", "0013_ryoiku"),
        ("reservations", "0005_booking_mode_and_guests"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["date", "start_time", "created_at"],
                "verbose_name": "予約",
                "verbose_name_plural": "予約",
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="start_time",
            field=models.TimeField(blank=True, null=True, verbose_name="開始時刻"),
        ),
        migrations.AddField(
            model_name="reservationsetting",
            name="break_hours",
            field=models.JSONField(
                blank=True,
                default=reservations.models.default_break_hours,
                help_text="昼休みなど。例：12",
                verbose_name="枠を置かない時刻",
            ),
        ),
        migrations.AddField(
            model_name="reservationsetting",
            name="holiday_first_hour",
            field=models.PositiveSmallIntegerField(
                default=9, verbose_name="土日祝の最初の枠（時）"
            ),
        ),
        migrations.AddField(
            model_name="reservationsetting",
            name="holiday_last_hour",
            field=models.PositiveSmallIntegerField(
                default=17, verbose_name="土日祝の最後の枠（時）"
            ),
        ),
        migrations.AddField(
            model_name="reservationsetting",
            name="slot_capacity",
            field=models.PositiveSmallIntegerField(default=3, verbose_name="1枠の人数"),
        ),
        migrations.AddField(
            model_name="reservationsetting",
            name="slot_minutes",
            field=models.PositiveSmallIntegerField(
                default=45, verbose_name="1枠の長さ（分）"
            ),
        ),
        migrations.AddField(
            model_name="reservationsetting",
            name="slot_mode",
            field=models.BooleanField(
                default=False,
                help_text="1日の枠ではなく、1時間ごとの枠（1枠45分）に人数の上限を置きます。月予約利用希望から月間予定表を作れます。",
                verbose_name="時間枠で予約する",
            ),
        ),
        migrations.AddField(
            model_name="reservationsetting",
            name="weekday_first_hour",
            field=models.PositiveSmallIntegerField(
                default=10, verbose_name="平日の最初の枠（時）"
            ),
        ),
        migrations.AddField(
            model_name="reservationsetting",
            name="weekday_last_hour",
            field=models.PositiveSmallIntegerField(
                default=18, verbose_name="平日の最後の枠（時）"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="source",
            field=models.CharField(
                choices=[
                    ("staff", "職員"),
                    ("line", "公式LINE"),
                    ("web", "顧客ページ"),
                    ("group", "スタッフのグループ"),
                    ("request", "月予約利用希望"),
                ],
                default="staff",
                max_length=10,
                verbose_name="入口",
            ),
        ),
        migrations.CreateModel(
            name="MonthlyRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="年")),
                ("month", models.PositiveSmallIntegerField(verbose_name="月")),
                (
                    "desired_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="希望利用回数"
                    ),
                ),
                (
                    "wishes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="可能な日時"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="備考"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("staff", "職員が転記"), ("web", "顧客ページ")],
                        default="staff",
                        max_length=10,
                        verbose_name="入口",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_requests",
                        to="beneficiaries.beneficiary",
                        verbose_name="利用者",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monthly_requests",
                        to="reservations.customer",
                        verbose_name="送った顧客",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_requests",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "月予約利用希望",
                "verbose_name_plural": "月予約利用希望",
                "ordering": ["-year", "-month", "beneficiary__last_name_kana"],
                "unique_together": {("beneficiary", "year", "month")},
            },
        ),
    ]
