# Generated by Django 6.1.1 on 2026-09-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0006_ryoiku"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservationnotice",
            name="kind",
            field=models.CharField(
                choices=[
                    ("accepted", "受付"),
                    ("waitlisted", "キャンセル待ち"),
                    ("promoted", "繰り上げ確定"),
                    ("cancelled", "取消"),
                    ("moved", "日にちの変更"),
                    ("declined", "お断り"),
                    ("reminder", "前日のお知らせ"),
                    ("vacancy", "空き枠"),
                    ("group", "予約の増減（グループ）"),
                    ("wish", "利用希望の入力のお願い"),
                ],
                max_length=20,
                verbose_name="種類",
            ),
        ),
    ]
