# Generated by Django 6.1.1 on 2026-09-23 03:07

import django.db.models.deletion
import facilities.uploads
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0009_planbook"),
        ("facilities", "0013_ryoiku"),
        ("reservations", "0007_notice_kind_wish"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlyrequest",
            name="source",
            field=models.CharField(
                choices=[
                    ("staff", "職員が転記"),
                    ("web", "顧客ページ"),
                    ("photo", "用紙の写真から"),
                ],
                default="staff",
                max_length=10,
                verbose_name="入口",
            ),
        ),
        migrations.CreateModel(
            name="RequestScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="年")),
                ("month", models.PositiveSmallIntegerField(verbose_name="月")),
                (
                    "image",
                    models.ImageField(
                        upload_to=facilities.uploads.request_scan_upload_to,
                        verbose_name="用紙の写真",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "未読み取り"),
                            ("extracted", "確認待ち"),
                            ("imported", "反映ずみ"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="状態",
                    ),
                ),
                (
                    "extracted",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="読み取り結果"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="エラー")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("extracted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_scans",
                        to="beneficiaries.beneficiary",
                        verbose_name="利用者",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_scans",
                        to="facilities.facility",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scans",
                        to="reservations.monthlyrequest",
                        verbose_name="反映した利用希望",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "利用希望の用紙（写真）",
                "verbose_name_plural": "利用希望の用紙（写真）",
                "ordering": ["created_at"],
            },
        ),
    ]
