# Generated by Django 6.1.1 on 2026-09-26 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0017_ryoiku_layout_trial"),
        ("reservations", "0012_monthlyrequest_source_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="attendance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "未入力"),
                    ("attended", "来た"),
                    ("absent", "欠席"),
                    ("cancelled", "キャンセル"),
                ],
                default="",
                max_length=10,
                verbose_name="実績",
            ),
        ),
        migrations.CreateModel(
            name="StaffShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="担当欄に出す名前（例：土田）",
                        max_length=30,
                        verbose_name="名前",
                    ),
                ),
                (
                    "weekdays",
                    models.JSONField(blank=True, default=list, verbose_name="曜日"),
                ),
                (
                    "part",
                    models.CharField(
                        choices=[("all", "終日"), ("am", "午前"), ("pm", "午後")],
                        default="all",
                        max_length=5,
                        verbose_name="時間帯",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="使う")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_shifts",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "職員のシフト",
                "verbose_name_plural": "職員のシフト",
                "ordering": ["pk"],
            },
        ),
    ]
