# Generated by Django 6.1.1 on 2026-09-30 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0013_attendance_staffshift"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffshift",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
