# Generated by Django 6.1.1 on 2026-10-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0014_staffshift_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="share_seat",
            field=models.BooleanField(
                default=False, verbose_name="きょうだいと1枠にまとめる"
            ),
        ),
    ]
