# Generated by Django 6.1.1 on 2026-10-09 01:25

from decimal import Decimal

from django.db import migrations, models


def ryoiku_capacity(apps, schema_editor):
    """ゆあーずは定員 10・1日 15 人まで・3か月平均 12.9 人までにする（未設定のときだけ。オウルなどほかの事業所は施設ごとに入れる）"""
    Setting = apps.get_model('reservations', 'ReservationSetting')
    Setting.objects.filter(facility__name='発達支援ルーム　ゆあーず', legal_capacity=0).update(
        legal_capacity=10, day_limit=15, avg_limit=Decimal('12.9'))


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0015_reservation_share_seat"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationsetting",
            name="avg_limit",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="0 なら定員 11 以下は定員＋3、12 以上は定員の 125%",
                max_digits=4,
                verbose_name="3か月平均の上限（人／日）",
            ),
        ),
        migrations.AddField(
            model_name="reservationsetting",
            name="day_limit",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="0 なら定員の 150%（定員 10 なら 15）",
                verbose_name="1日の上限（人）",
            ),
        ),
        migrations.AddField(
            model_name="reservationsetting",
            name="legal_capacity",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="指定を受けた定員。0 なら定員の知らせを出さない",
                verbose_name="定員（人／日）",
            ),
        ),
        migrations.RunPython(ryoiku_capacity, migrations.RunPython.noop),
    ]
