# Generated by Django 6.1.1 on 2026-10-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0016_capacity_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationsetting",
            name="line_friend_url",
            field=models.URLField(
                blank=True,
                help_text="https://lin.ee/… など。保護者向けの案内紙に QR コードで載せる",
                verbose_name="公式LINEの友だち追加のアドレス",
            ),
        ),
    ]
