# Generated by Django 6.1.1 on 2026-09-13 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facilities", "0004_supportcontenttag_price"),
        ("records", "0006_activity_viewpoints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferenceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="資料名")),
                (
                    "file",
                    models.FileField(
                        upload_to="reference_docs/%Y/%m/", verbose_name="PDFファイル"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="アップロード日時"
                    ),
                ),
                (
                    "indexed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ベクトル化日時"
                    ),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(default=0, verbose_name="ページ数"),
                ),
                (
                    "chunk_count",
                    models.PositiveIntegerField(default=0, verbose_name="チャンク数"),
                ),
                ("error", models.TextField(blank=True, verbose_name="エラー")),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_documents",
                        to="facilities.facility",
                        verbose_name="施設",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="アップロード者",
                    ),
                ),
            ],
            options={
                "verbose_name": "算定要件資料",
                "verbose_name_plural": "算定要件資料",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                ("page", models.PositiveIntegerField(default=1)),
                ("text", models.TextField()),
                ("terms", models.JSONField(default=dict)),
                ("length", models.PositiveIntegerField(default=0)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="ai_assist.referencedocument",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "index"],
            },
        ),
        migrations.CreateModel(
            name="AddonSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="提案理由")),
                (
                    "evidence",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="根拠資料"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "未対応"),
                            ("adopted", "採用"),
                            ("dismissed", "見送り"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="状態",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "addon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facilities.addonmaster",
                        verbose_name="加算",
                    ),
                ),
                (
                    "daily_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addon_suggestions",
                        to="records.dailyrecord",
                        verbose_name="日誌",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="判断した職員",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facilities.facility",
                        verbose_name="施設",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI加算提案",
                "verbose_name_plural": "AI加算提案",
                "ordering": ["-created_at"],
                "unique_together": {("daily_record", "addon")},
            },
        ),
    ]
