# Generated by Django 6.1.1 on 2026-09-14 14:51

import facilities.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencedocument",
            name="file",
            field=models.FileField(
                upload_to=facilities.uploads.reference_doc_upload_to,
                verbose_name="PDFファイル",
            ),
        ),
    ]
