# Generated by Django 6.1.1 on 2026-09-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffaccount",
            name="ui_theme",
            field=models.CharField(
                choices=[
                    ("standard", "スタンダード"),
                    ("large", "大きな文字"),
                    ("stylish", "スタイリッシュ"),
                    ("simple", "かんたん3ステップ"),
                ],
                default="standard",
                max_length=20,
                verbose_name="画面の見た目",
            ),
        ),
    ]
