# Generated by Django 6.1.1 on 2026-09-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_ui_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffaccount",
            name="ui_prefs",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="表示の細かい設定"
            ),
        ),
    ]
