# Generated by Django 6.1.1 on 2026-09-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_ui_prefs"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffaccount",
            name="is_developer",
            field=models.BooleanField(
                default=False,
                help_text="すべての事業所にアクセスでき、画面上で事業所を切り替えられます。",
                verbose_name="開発向けユーザー",
            ),
        ),
    ]
