# Generated by Django 6.1.1 on 2026-09-14 13:45

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_is_developer"),
        ("facilities", "0007_facility_form_set"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=accounts.models._new_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "管理者"),
                            ("child_dev_manager", "児発管"),
                            ("staff", "職員"),
                            ("office", "事務"),
                        ],
                        default="staff",
                        max_length=20,
                        verbose_name="権限区分",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="誰に渡すか（例：4月入職の3名）",
                        max_length=100,
                        verbose_name="メモ",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="使える回数"
                    ),
                ),
                (
                    "used_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="使われた回数"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="有効期限")),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="発行者",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="facilities.facility",
                        verbose_name="施設",
                    ),
                ),
            ],
            options={
                "verbose_name": "職員の招待リンク",
                "verbose_name_plural": "職員の招待リンク",
                "ordering": ["-created_at"],
            },
        ),
    ]
