# Generated by Django 6.1.1 on 2026-09-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_staff_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffaccount",
            name="signup_pending",
            field=models.BooleanField(default=False, verbose_name="承認待ち"),
        ),
    ]
