# Generated by Django 6.1.1 on 2026-10-06 11:05

import django.db.models.deletion
import surveys.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facilities", "0020_use_survey"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("guardian", "保護者評価"),
                            ("staff", "従業者評価（職員）"),
                        ],
                        default="guardian",
                        max_length=10,
                        verbose_name="種類",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("jihatsu", "児童発達支援"),
                            ("houday", "放課後等デイサービス"),
                        ],
                        default="jihatsu",
                        max_length=10,
                        verbose_name="事業の種類",
                    ),
                ),
                (
                    "fiscal_year",
                    models.PositiveSmallIntegerField(
                        default=surveys.models.fiscal_year_of, verbose_name="年度"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="件名")),
                (
                    "intro",
                    models.TextField(blank=True, verbose_name="回答ページの案内文"),
                ),
                (
                    "questions",
                    models.JSONField(blank=True, default=list, verbose_name="設問"),
                ),
                (
                    "token",
                    models.CharField(
                        default=surveys.models.new_survey_token,
                        max_length=128,
                        unique=True,
                        verbose_name="回答ページのアドレス",
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=True, verbose_name="回答を受け付けている"
                    ),
                ),
                (
                    "closes_on",
                    models.DateField(blank=True, null=True, verbose_name="締め切り"),
                ),
                (
                    "line_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="LINE で送った日時"
                    ),
                ),
                (
                    "line_sent_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="LINE で送った人数"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveys",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "アンケート",
                "verbose_name_plural": "アンケート",
                "ordering": ["-fiscal_year", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answers",
                    models.JSONField(blank=True, default=dict, verbose_name="答え"),
                ),
                (
                    "comments",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="設問ごとの意見"
                    ),
                ),
                (
                    "free_text",
                    models.TextField(blank=True, verbose_name="ご意見・ご要望"),
                ),
                (
                    "respondent",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="お名前（任意）"
                    ),
                ),
                ("client_key", models.CharField(blank=True, max_length=64)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="surveys.survey",
                    ),
                ),
            ],
            options={
                "verbose_name": "アンケートの回答",
                "verbose_name_plural": "アンケートの回答",
                "ordering": ["submitted_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SelfEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fiscal_year",
                    models.PositiveSmallIntegerField(
                        default=surveys.models.fiscal_year_of, verbose_name="年度"
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("jihatsu", "児童発達支援"),
                            ("houday", "放課後等デイサービス"),
                        ],
                        default="jihatsu",
                        max_length=10,
                        verbose_name="事業の種類",
                    ),
                ),
                (
                    "items",
                    models.JSONField(
                        blank=True, default=list, verbose_name="自己評価の項目"
                    ),
                ),
                (
                    "guardian_items",
                    models.JSONField(
                        blank=True, default=list, verbose_name="保護者評価への改善目標"
                    ),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        verbose_name="総括（事業所全体としての評価と改善の方向）",
                    ),
                ),
                (
                    "published_on",
                    models.DateField(blank=True, null=True, verbose_name="公表日"),
                ),
                (
                    "publish_note",
                    models.CharField(
                        blank=True,
                        help_text="ホームページの URL・会報の号など",
                        max_length=200,
                        verbose_name="公表の方法",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="self_evaluations",
                        to="facilities.facility",
                    ),
                ),
                (
                    "guardian_survey",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="surveys.survey",
                        verbose_name="保護者評価",
                    ),
                ),
                (
                    "staff_survey",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="surveys.survey",
                        verbose_name="従業者評価",
                    ),
                ),
            ],
            options={
                "verbose_name": "自己評価",
                "verbose_name_plural": "自己評価",
                "ordering": ["-fiscal_year", "-pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("facility", "fiscal_year", "service"),
                        name="uniq_self_evaluation",
                    )
                ],
            },
        ),
    ]
