# Generated by Django 6.1.1 on 2026-09-05 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "beneficiaries",
            "0002_beneficiary_weekday_fri_beneficiary_weekday_mon_and_more",
        ),
        ("facilities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="タグ名")),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="表示順"),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_tags",
                        to="facilities.facility",
                        verbose_name="施設",
                    ),
                ),
            ],
            options={
                "verbose_name": "活動タグ",
                "verbose_name_plural": "活動タグ",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="DailyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="記録日")),
                (
                    "observation_memo",
                    models.TextField(blank=True, verbose_name="観察メモ"),
                ),
                ("support_memo", models.TextField(blank=True, verbose_name="支援メモ")),
                (
                    "reaction_memo",
                    models.TextField(blank=True, verbose_name="反応メモ"),
                ),
                (
                    "observation_text",
                    models.TextField(blank=True, verbose_name="観察記録"),
                ),
                ("support_text", models.TextField(blank=True, verbose_name="支援記録")),
                (
                    "reaction_text",
                    models.TextField(blank=True, verbose_name="反応記録"),
                ),
                (
                    "parent_message_draft",
                    models.TextField(
                        blank=True, verbose_name="保護者向けメッセージ下書き"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "下書き"), ("confirmed", "確定")],
                        default="draft",
                        max_length=10,
                        verbose_name="状態",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity_tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="records",
                        to="records.activitytag",
                        verbose_name="活動タグ",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="authored_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="記録者",
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_records",
                        to="beneficiaries.beneficiary",
                        verbose_name="利用者",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facilities.facility",
                        verbose_name="施設",
                    ),
                ),
            ],
            options={
                "verbose_name": "日誌",
                "verbose_name_plural": "日誌",
                "ordering": ["-date"],
                "unique_together": {("beneficiary", "date")},
            },
        ),
    ]
