# Generated by Django 6.1.1 on 2026-09-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "facilities",
            "0002_facility_base_unit_count_facility_is_new_facility_r8_and_more",
        ),
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitytag",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="有効"),
        ),
        migrations.AddField(
            model_name="activitytag",
            name="price",
            field=models.PositiveIntegerField(
                default=0,
                help_text="おやつ・食事など実費請求する場合に1回あたりの金額を入力。不要なら0のまま。",
                verbose_name="実費単価（円/回）",
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="domain_cognition_behavior",
            field=models.BooleanField(default=False, verbose_name="認知・行動"),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="domain_health_life",
            field=models.BooleanField(default=False, verbose_name="健康・生活"),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="domain_language_comm",
            field=models.BooleanField(
                default=False, verbose_name="言語・コミュニケーション"
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="domain_motor_sensory",
            field=models.BooleanField(default=False, verbose_name="運動・感覚"),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="domain_social",
            field=models.BooleanField(default=False, verbose_name="人間関係・社会性"),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="entry_time",
            field=models.TimeField(blank=True, null=True, verbose_name="入室時間"),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="exit_time",
            field=models.TimeField(blank=True, null=True, verbose_name="退室時間"),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="health_condition",
            field=models.CharField(
                choices=[("good", "良好"), ("normal", "普通"), ("special", "特記あり")],
                default="good",
                max_length=10,
                verbose_name="体調",
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="health_note",
            field=models.TextField(blank=True, verbose_name="体調詳細"),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="support_tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="records",
                to="facilities.supportcontenttag",
                verbose_name="支援内容タグ",
            ),
        ),
    ]
