# Generated by Django 6.1.1 on 2026-09-09 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0003_addonmaster_facilityaddonsetting"),
        ("records", "0002_activitytag_is_active_activitytag_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyRecordPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="daily_record_photos/%Y/%m/", verbose_name="写真"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="表示順"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "daily_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="records.dailyrecord",
                        verbose_name="日誌",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facilities.facility",
                        verbose_name="施設",
                    ),
                ),
            ],
            options={
                "verbose_name": "日誌写真",
                "verbose_name_plural": "日誌写真",
                "ordering": ["order", "uploaded_at"],
            },
        ),
    ]
