# Generated by Django 6.1.1 on 2026-09-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0004_add_staff_memo"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyrecord",
            name="activity_aim",
            field=models.TextField(blank=True, verbose_name="めあて・観点"),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="activity_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="活動"),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="activity_reflection",
            field=models.TextField(blank=True, verbose_name="考察"),
        ),
    ]
