# Generated by Django 6.1.1 on 2026-09-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0005_add_activity_aim_reflection"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyrecord",
            name="activity_viewpoints",
            field=models.JSONField(
                blank=True, default=list, verbose_name="観点（はい／いいえ）"
            ),
        ),
        migrations.AlterField(
            model_name="dailyrecord",
            name="activity_aim",
            field=models.TextField(blank=True, verbose_name="めあて"),
        ),
    ]
