# Generated by Django 6.1.1 on 2026-09-13 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0005_add_unique_constraint_to_line_registration_code"),
        ("facilities", "0005_facility_branding_terms"),
        ("records", "0006_activity_viewpoints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="テンプレート名"),
                ),
                (
                    "activity_name",
                    models.CharField(blank=True, max_length=100, verbose_name="活動"),
                ),
                ("activity_aim", models.TextField(blank=True, verbose_name="めあて")),
                (
                    "activity_viewpoints",
                    models.JSONField(blank=True, default=list, verbose_name="観点"),
                ),
                (
                    "activity_reflection",
                    models.TextField(blank=True, verbose_name="考察"),
                ),
                ("observation_memo", models.TextField(blank=True, verbose_name="メモ")),
                (
                    "observation_text",
                    models.TextField(blank=True, verbose_name="観察・活動内容"),
                ),
                ("support_text", models.TextField(blank=True, verbose_name="支援内容")),
                (
                    "reaction_text",
                    models.TextField(blank=True, verbose_name="本人の反応"),
                ),
                (
                    "parent_message_draft",
                    models.TextField(blank=True, verbose_name="保護者向けメッセージ"),
                ),
                (
                    "domains",
                    models.JSONField(blank=True, default=list, verbose_name="5領域"),
                ),
                (
                    "use_count",
                    models.PositiveIntegerField(default=0, verbose_name="使用回数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity_tags",
                    models.ManyToManyField(
                        blank=True, to="records.activitytag", verbose_name="活動タグ"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record_templates",
                        to="facilities.facility",
                        verbose_name="施設",
                    ),
                ),
                (
                    "source_beneficiary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="beneficiaries.beneficiary",
                        verbose_name="元になった利用者",
                    ),
                ),
                (
                    "support_tags",
                    models.ManyToManyField(
                        blank=True,
                        to="facilities.supportcontenttag",
                        verbose_name="支援内容タグ",
                    ),
                ),
            ],
            options={
                "verbose_name": "日誌テンプレート",
                "verbose_name_plural": "日誌テンプレート",
                "ordering": ["-updated_at"],
            },
        ),
    ]
