# Generated by Django 6.1.1 on 2026-09-14 14:51

import facilities.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0008_paper_scan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyrecordphoto",
            name="photo",
            field=models.ImageField(
                upload_to=facilities.uploads.photo_upload_to, verbose_name="写真"
            ),
        ),
        migrations.AlterField(
            model_name="paperscan",
            name="image",
            field=models.ImageField(
                upload_to=facilities.uploads.paper_scan_upload_to, verbose_name="画像"
            ),
        ),
    ]
