# Generated by Django 6.1.1 on 2026-09-18 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0009_uuid_uploads"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyrecord",
            name="collaboration_note",
            field=models.TextField(blank=True, verbose_name="連携の内容"),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="record_kind",
            field=models.CharField(
                choices=[
                    ("standard", "普通用"),
                    ("severe", "重身用（重症心身障害児）"),
                ],
                default="standard",
                max_length=10,
                verbose_name="日誌の種類",
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="severe_care",
            field=models.JSONField(blank=True, default=dict, verbose_name="重身の記録"),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="special_support_end",
            field=models.TimeField(
                blank=True, null=True, verbose_name="専門的支援 終了"
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="special_support_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="special_supports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="専門的支援の担当者",
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="special_support_start",
            field=models.TimeField(
                blank=True, null=True, verbose_name="専門的支援 開始"
            ),
        ),
    ]
