# Generated by Django 6.1.1 on 2026-10-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0010_severe_addons_offices"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyrecord",
            name="good_example_note",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="良い例の理由（どこが良いか）"
            ),
        ),
        migrations.AddField(
            model_name="dailyrecord",
            name="is_good_example",
            field=models.BooleanField(default=False, verbose_name="良い記録の例に出す"),
        ),
    ]
