# Generated by Django 6.1.1 on 2026-09-19 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beneficiaries", "0009_planbook"),
        ("facilities", "0012_planbook"),
        ("support_plans", "0004_concurrency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="支援期間（開始）"
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="支援期間（終了）"
                    ),
                ),
                (
                    "interview_date",
                    models.DateField(blank=True, null=True, verbose_name="面談実施日"),
                ),
                (
                    "created_date",
                    models.DateField(blank=True, null=True, verbose_name="作成日"),
                ),
                (
                    "home_parent",
                    models.TextField(
                        blank=True, verbose_name="家庭での様子（親御様から）"
                    ),
                ),
                (
                    "home_staff",
                    models.TextField(
                        blank=True, verbose_name="家庭での様子（スタッフの支援策）"
                    ),
                ),
                (
                    "school_parent",
                    models.TextField(
                        blank=True, verbose_name="学校等での様子（親御様から）"
                    ),
                ),
                (
                    "school_staff",
                    models.TextField(
                        blank=True, verbose_name="学校等での様子（スタッフの支援策）"
                    ),
                ),
                (
                    "social_parent",
                    models.TextField(
                        blank=True, verbose_name="対人など協調性（親御様から）"
                    ),
                ),
                (
                    "social_staff",
                    models.TextField(
                        blank=True, verbose_name="対人など協調性（スタッフの支援策）"
                    ),
                ),
                (
                    "future_wishes",
                    models.TextField(
                        blank=True, verbose_name="将来の展望・親御様からの要望"
                    ),
                ),
                (
                    "other_wishes",
                    models.TextField(
                        blank=True, verbose_name="その他施設への親御様からの要望"
                    ),
                ),
                (
                    "schedule",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="提供時間（曜日ごと）"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="特記事項")),
                (
                    "extension_reason",
                    models.TextField(blank=True, verbose_name="延長を必要とする理由"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完了日時"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者（児童発達支援管理責任者）",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="完了者",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="当面談に参加したスタッフ",
                    ),
                ),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview",
                        to="support_plans.supportplan",
                        verbose_name="計画",
                    ),
                ),
            ],
            options={
                "verbose_name": "面談記録",
                "verbose_name_plural": "面談記録",
            },
        ),
        migrations.CreateModel(
            name="ContactNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("staff", "施設から"), ("guardian", "保護者から")],
                        default="staff",
                        max_length=10,
                        verbose_name="送信者",
                    ),
                ),
                ("body", models.TextField(verbose_name="内容")),
                (
                    "line_sent",
                    models.BooleanField(default=False, verbose_name="LINEで送った"),
                ),
                (
                    "line_error",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="LINE送信エラー"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=True, verbose_name="既読（保護者からの分）"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="日時"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="記入した職員",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facilities.facility",
                        verbose_name="施設",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_notes",
                        to="beneficiaries.guardian",
                        verbose_name="保護者",
                    ),
                ),
            ],
            options={
                "verbose_name": "連絡帳",
                "verbose_name_plural": "連絡帳",
                "ordering": ["created_at", "pk"],
                "indexes": [
                    models.Index(
                        fields=["facility", "guardian", "created_at"],
                        name="planbook_co_facilit_6ef5f8_idx",
                    )
                ],
            },
        ),
    ]
