# Generated by Django 6.1.1 on 2026-09-06 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beneficiaries", "0003_add_guardian_line_linked"),
        ("facilities", "0003_addonmaster_facilityaddonsetting"),
        ("records", "0002_activitytag_is_active_activitytag_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LineDeliveryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="送信内容")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="送信日時"),
                ),
                (
                    "is_success",
                    models.BooleanField(default=False, verbose_name="送信成功"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="エラー内容"),
                ),
                (
                    "daily_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="records.dailyrecord",
                        verbose_name="関連日次記録",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facilities.facility",
                        verbose_name="施設",
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="beneficiaries.guardian",
                        verbose_name="送信先保護者",
                    ),
                ),
            ],
            options={
                "verbose_name": "LINE配信履歴",
                "verbose_name_plural": "LINE配信履歴",
                "ordering": ["-sent_at"],
            },
        ),
    ]
