# Generated by Django 6.1.1 on 2026-09-05 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "beneficiaries",
            "0002_beneficiary_weekday_fri_beneficiary_weekday_mon_and_more",
        ),
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="来所日")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "予定"),
                            ("attended", "来所"),
                            ("absent", "欠席"),
                            ("canceled", "キャンセル"),
                        ],
                        default="scheduled",
                        max_length=10,
                        verbose_name="状態",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="メモ"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_visits",
                        to="beneficiaries.beneficiary",
                        verbose_name="利用者",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facilities.facility",
                        verbose_name="施設",
                    ),
                ),
            ],
            options={
                "verbose_name": "来所予定",
                "verbose_name_plural": "来所予定",
                "ordering": ["date", "beneficiary__last_name_kana"],
                "unique_together": {("beneficiary", "date")},
            },
        ),
    ]
