# Generated by Django 6.1.1 on 2026-09-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledvisit",
            name="note",
        ),
        migrations.AddField(
            model_name="scheduledvisit",
            name="has_dropoff",
            field=models.BooleanField(default=False, verbose_name="送迎あり（送り）"),
        ),
        migrations.AddField(
            model_name="scheduledvisit",
            name="has_pickup",
            field=models.BooleanField(default=False, verbose_name="送迎あり（迎え）"),
        ),
        migrations.AddField(
            model_name="scheduledvisit",
            name="notes",
            field=models.TextField(blank=True, verbose_name="備考"),
        ),
        migrations.AlterField(
            model_name="scheduledvisit",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "予定"),
                    ("attended", "来所"),
                    ("absent", "欠席"),
                    ("transferred", "振替"),
                ],
                default="scheduled",
                max_length=20,
                verbose_name="状態",
            ),
        ),
    ]
