# Generated by Django 6.1.1 on 2026-10-06 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beneficiaries", "0016_developmentassessment"),
        ("facilities", "0019_transport_dev_assessment"),
        ("reservations", "0014_staffshift_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="運転手の名前")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="電話番号"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="出られる曜日・時間など",
                        max_length=200,
                        verbose_name="備考",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="在籍中")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="並び順"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drivers",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "運転手",
                "verbose_name_plural": "運転手",
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="例：ハイエース（白）・軽ワゴン",
                        max_length=50,
                        verbose_name="車両名",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="0 なら未設定。配車表で人数が超えると色が付きます",
                        verbose_name="乗れる人数（運転手を除く）",
                    ),
                ),
                (
                    "plate",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="ナンバー・色など"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="チャイルドシートの数・車いす対応など",
                        max_length=200,
                        verbose_name="備考",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="使っている"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="並び順"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_vehicles",
                        to="transport.driver",
                        verbose_name="いつもの運転手",
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="facilities.facility",
                    ),
                ),
            ],
            options={
                "verbose_name": "車両",
                "verbose_name_plural": "車両",
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="TransportProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pickup", models.BooleanField(default=False, verbose_name="迎えあり")),
                (
                    "pickup_place",
                    models.CharField(
                        blank=True,
                        help_text="学校名・自宅など",
                        max_length=200,
                        verbose_name="迎えの場所",
                    ),
                ),
                (
                    "pickup_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="迎えの目安の時刻"
                    ),
                ),
                (
                    "dropoff",
                    models.BooleanField(default=False, verbose_name="送りあり"),
                ),
                (
                    "dropoff_place",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="送りの場所"
                    ),
                ),
                (
                    "dropoff_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="送りの目安の時刻"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="チャイルドシート・酔いやすい・引き渡しの相手など",
                        max_length=200,
                        verbose_name="送迎の注意",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transport",
                        to="beneficiaries.beneficiary",
                        verbose_name="利用者",
                    ),
                ),
                (
                    "default_vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regulars",
                        to="transport.vehicle",
                        verbose_name="いつもの車両",
                    ),
                ),
            ],
            options={
                "verbose_name": "送迎の設定",
                "verbose_name_plural": "送迎の設定",
            },
        ),
        migrations.CreateModel(
            name="TransportAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("pickup", "迎え"), ("dropoff", "送り")],
                        max_length=10,
                        verbose_name="迎え／送り",
                    ),
                ),
                ("time", models.TimeField(blank=True, null=True, verbose_name="時刻")),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="場所（この日だけ変えるとき）",
                    ),
                ),
                (
                    "skip",
                    models.BooleanField(default=False, verbose_name="この日は送迎なし"),
                ),
                (
                    "added",
                    models.BooleanField(
                        default=False, verbose_name="設定に無いがこの日だけ送迎する"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=200, verbose_name="備考"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transport.driver",
                        verbose_name="運転手",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transports",
                        to="reservations.reservation",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="transport.vehicle",
                        verbose_name="車両",
                    ),
                ),
            ],
            options={
                "verbose_name": "配車",
                "verbose_name_plural": "配車",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reservation", "direction"),
                        name="uniq_transport_assignment",
                    )
                ],
            },
        ),
    ]
