# Generated by Django 6.1.1 on 2026-09-20 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beneficiaries", "0009_planbook"),
        ("facilities", "0013_ryoiku"),
        ("reservations", "0006_ryoiku"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TherapyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cautions", models.TextField(blank=True, verbose_name="留意点")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapy_profile",
                        to="beneficiaries.beneficiary",
                        verbose_name="利用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "療育の留意点",
                "verbose_name_plural": "療育の留意点",
            },
        ),
        migrations.CreateModel(
            name="TherapyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="時刻")),
                (
                    "staff_name",
                    models.CharField(
                        blank=True,
                        help_text="アカウントのない職員や、退職した職員の名前を残すとき",
                        max_length=50,
                        verbose_name="担当（名前）",
                    ),
                ),
                (
                    "activities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="やったこと（①〜⑤）"
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="記録")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapy_records",
                        to="beneficiaries.beneficiary",
                        verbose_name="利用者",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="therapy_records",
                        to="facilities.facility",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="therapy_records",
                        to="reservations.reservation",
                        verbose_name="もとになった予約",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="therapy_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="担当",
                    ),
                ),
            ],
            options={
                "verbose_name": "療育記録",
                "verbose_name_plural": "療育記録",
                "ordering": ["-date", "-time", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["facility", "date"],
                        name="therapy_the_facilit_6ab53b_idx",
                    )
                ],
            },
        ),
    ]
