# Generated by Django 6.1.1 on 2026-10-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("therapy", "0001_ryoiku"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapyrecord",
            name="situation",
            field=models.TextField(blank=True, verbose_name="様子（どうだったか）"),
        ),
        migrations.AlterField(
            model_name="therapyrecord",
            name="body",
            field=models.TextField(blank=True, verbose_name="記録（事実：したこと）"),
        ),
    ]
